import { archiveCategory, createCategory, toggleCategory, updateCategory } from "@/app/actions/categories";
import { requireAdmin } from "@/lib/auth";
import { UpdatedAt } from "@/components/updated-at";
import { databaseErrorMessages } from "@/lib/database-errors";

const errors: Record<string, string> = { ...databaseErrorMessages, invalid_category: "Enter a valid category name.", duplicate_slug: "That category name or slug already exists.", save_failed: "Category could not be saved because of an unexpected database error. Please try again.", category_in_use: "This category is assigned to staged content and cannot be archived.", delete_failed: "Category could not be archived." };
const successes: Record<string, string> = { created: "Category created.", updated: "Category updated.", archived: "Category archived safely." };

export default async function CategoriesPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const { error, success } = await searchParams;
  const { supabase } = await requireAdmin();
  const { data: categories, error: loadError } = await supabase.from("cms_categories").select("*").is("deleted_at", null).order("sort_order").order("name");
  return <><section className="page-heading"><div><p className="eyebrow accent">LIBRARY STRUCTURE</p><h1>Categories</h1><p className="muted">Organize staged movies and shows. This does not change the live app.</p></div></section>{error && <div className="alert error">{errors[error] ?? "Something went wrong."}</div>}{success && <div className="alert success">{successes[success] ?? "Saved successfully."}</div>}{loadError && <div className="alert error">Could not load categories.</div>}<section className="manage-grid"><form action={createCategory} className="panel form-panel"><div><p className="eyebrow">NEW CATEGORY</p><h2>Add category</h2></div><label>Name<input name="name" required maxLength={80} placeholder="Documentaries" /></label><label>Slug<input name="slug" maxLength={100} placeholder="Auto-generated from name" /></label><label>Description<textarea name="description" rows={4} placeholder="Optional category description" /></label><label>Sort order<input name="sort_order" type="number" defaultValue="0" /></label><button className="button primary" type="submit">Create category</button></form><div className="panel"><div className="panel-title"><div><p className="eyebrow">STAGED CATEGORIES</p><h2>{categories?.length ?? 0} categories</h2></div></div><div className="record-list">{categories?.map((category) => <details className="record" key={category.id}><summary><div><strong>{category.name}</strong><small>/{category.slug}<UpdatedAt value={category.updated_at} /></small></div><span className={`badge ${category.is_active ? "free" : "premium"}`}>{category.is_active ? "Active" : "Inactive"}</span></summary><form action={updateCategory} className="inline-form"><input name="id" type="hidden" value={category.id} /><label>Name<input name="name" defaultValue={category.name} required /></label><label>Slug<input name="slug" defaultValue={category.slug} required /></label><label>Description<textarea name="description" defaultValue={category.description ?? ""} rows={3} /></label><label>Sort order<input name="sort_order" type="number" defaultValue={category.sort_order} /></label><button className="button primary" type="submit">Save changes</button></form><div className="record-actions"><form action={toggleCategory}><input name="id" type="hidden" value={category.id} /><input name="is_active" type="hidden" value={String(category.is_active)} /><button className="button ghost" type="submit">{category.is_active ? "Set inactive" : "Set active"}</button></form><form action={archiveCategory}><input name="id" type="hidden" value={category.id} /><button className="button danger" type="submit">Archive</button></form></div></details>)}{!categories?.length && <div className="compact-empty">No staged categories yet.</div>}</div></div></section></>;
}
